apiVersion: v2
name: gateway-server
description: Boost Gateway Game Server Helm Chart
type: application
version: 1.0.0
appVersion: "3.3.2"
keywords:
  - game-server
  - boost-asio
  - cpp
  - gateway
maintainers:
  - name: BoostGateway Team
