apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-server.fullname" . }}
  labels:
    {{- include "gateway-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: game-port
      protocol: TCP
      name: game-port
    - port: {{ .Values.config.grpcPort }}
      targetPort: grpc-port
      protocol: TCP
      name: grpc-port
  selector:
    {{- include "gateway-server.selectorLabels" . | nindent 4 }}
